[package]
name = "wicked-waifus-control-panel"
version = "1.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_derive = "1.0.219"
serde_json = "1.0.140"
toml = "0.8.20"
